language: python
python:
  - 3.6.5
script:
  - python manage.py test
services:
  - postgresql
env:
  - SECRET_KEY='PIX4D!teST'
install:
  - pipenv install
notifications:
  email:
    recipients:
      - tourscapekeepers@gmail.com
    on_success: never
    on_failure: always
