language: python
python:
  - 3.6.5
script:
  - python manage.py test
services:
  - postgresql
env:
  - DJANGO=3.0.7 DB=postgresql
  - SECRET_KEY='PIX4D!teST'
install:
  - pip install pipenv
  - pipenv install
  - pip install -r requirements.txt
notifications:
  email:
    recipients:
      - tourscapekeepers@gmail.com
    on_success: never
    on_failure: always
