language: python
python:
  - 3.6.5
script:
  - python manage.py test
services:
  - postgresql
install:
  - pipenv install
notifications:
  email:
    recipients:
      - tourscapekeepers@gmail.com
    on_success: never
    on_failure: always
