# Generated by Django 3.0.2 on 2020-07-02 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('added_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['brand', 'model'],
            },
        ),
        migrations.CreateModel(
            name='CameraProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Product')),
                ('camera_resolution', models.CharField(blank=True, default='', max_length=8)),
            ],
            bases=('inventory.product',),
        ),
        migrations.CreateModel(
            name='DroneProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='inventory.Product')),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
            ],
            bases=('inventory.product',),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['added_date'], name='added_date_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='brand_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['model'], name='model_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand', 'model'], name='brand_model_idx'),
        ),
        migrations.AddField(
            model_name='droneproduct',
            name='compatible_camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.CameraProduct'),
        ),
    ]
