# Generated by Django 3.0.2 on 2020-07-02 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='droneproduct',
            name='compatible_camera',
        ),
        migrations.AddField(
            model_name='droneproduct',
            name='compatible_camera',
            field=models.ManyToManyField(to='inventory.CameraProduct'),
        ),
    ]
