# Generated by Django 3.0.2 on 2020-07-02 14:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200702_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameraproduct',
            name='camera_resolution',
            field=models.CharField(default='12 mpx', max_length=8),
        ),
        migrations.AlterField(
            model_name='droneproduct',
            name='serial_number',
            field=models.CharField(default='0000000000', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='added_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='Sony', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.CharField(default='Axxx', max_length=100),
        ),
    ]
